# Generated by Django 3.2.7 on 2023-06-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=200)),
                ('empemail', models.CharField(max_length=200)),
                ('empmobile', models.CharField(max_length=20)),
                ('empdesignation', models.CharField(max_length=200)),
                ('empsalary', models.IntegerField()),
            ],
        ),
    ]
